# The name of the database for storing data related to CommCare HQ
HQ_DATABASE_NAME = "HQ Data"

OAUTH2_DATABASE_NAME = "oauth2-server-data"

HQ_USER_ROLE_NAME = "hq_user"
GAMMA_ROLE_NAME = "Gamma"
READ_ONLY_ROLE_NAME = "hq_user_read_only"

# Permissions
SCHEMA_ACCESS_PERMISSION = "schema_access"
MENU_ACCESS_PERMISSION = "menu_access"

CAN_SHOW_PERMISSION = "can_show"
CAN_LIST_PERMISSION = "can_list"
CAN_GET_PERMISSION = "can_get"
CAN_EXTERNAL_METADATA_PERMISSION = "can_external_metadata"
CAN_EXTERNAL_METADATA_BY_NAME_PERMISSION = "can_external_metadata_by_name"
CAN_READ_PERMISSION = "can_read"

READ_ONLY_PERMISSIONS = [
    CAN_SHOW_PERMISSION,
    CAN_LIST_PERMISSION,
    CAN_GET_PERMISSION,
    CAN_EXTERNAL_METADATA_PERMISSION,
    CAN_EXTERNAL_METADATA_BY_NAME_PERMISSION,
    CAN_READ_PERMISSION,
]

CAN_WRITE_PERMISSION = "can_write"
CAN_EDIT_PERMISSION = "can_edit"
CAN_ADD_PERMISSION = "can_add"
CAN_DELETE_PERMISSIONS = "can_delete"


READ_ONLY_MENU_PERMISSIONS = {
    "Chart": READ_ONLY_PERMISSIONS,
    "Dataset": READ_ONLY_PERMISSIONS,
    "Dashboard": READ_ONLY_PERMISSIONS,
    "Datasource": READ_ONLY_PERMISSIONS,
    "OpenApi": READ_ONLY_PERMISSIONS,
    "Explore": READ_ONLY_PERMISSIONS,
    "Select a Domain": [MENU_ACCESS_PERMISSION],
    "Home": [MENU_ACCESS_PERMISSION],
    "Data": [MENU_ACCESS_PERMISSION],
    "Dashboards": [MENU_ACCESS_PERMISSION],
    "Charts": [MENU_ACCESS_PERMISSION],
    "Datasets": [MENU_ACCESS_PERMISSION],
    "ExploreFormDataRestApi": [CAN_READ_PERMISSION]
}

DOMAIN_PREFIX = "hqdomain_"
SESSION_USER_DOMAINS_KEY = "user_hq_domains"
SESSION_OAUTH_RESPONSE_KEY = "oauth_response"
SESSION_DOMAIN_ROLE_LAST_SYNCED_AT = "domain_role_last_synced_at"
